### ISSUE TITLE
Cannot read property 'Symbol(Symbol.iterator)' of undefined when importing isSameMonth

### ISSUE THREAD

**Issue by lucasfeliciano** [date-fns/date-fns#1074]
On our application start to crash and our kubernetes pods were restarting, then I checked papertrail logs and realized that we had this error popping up every time that we would deploy the application.

```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at _iterableToArrayLimit (/Users/lucasfeliciano/Project/.next/server/static/3qDzHatrKal7YRNVFxVEp/pages/_app.js:4164:131)
    at _slicedToArray (/Users/lucasfeliciano/Project/.next/server/static/3qDzHatrKal7YRNVFxVEp/pages/_app.js:4160:66)
    at Function._callee$ (/Users/lucasfeliciano/Project/.next/server/static/3qDzHatrKal7YRNVFxVEp/pages/_app.js:4344:35)
    at tryCatch (/Users/lucasfeliciano/Project/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/lucasfeliciano/Project/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/lucasfeliciano/Project/node_modules/regenerator-runtime/runtime.js:114:21)
    at _app_asyncGeneratorStep (/Users/lucasfeliciano/Project/.next/server/static/3qDzHatrKal7YRNVFxVEp/pages/_app.js:4168:108)
    at _next (/Users/lucasfeliciano/Project/.next/server/static/3qDzHatrKal7YRNVFxVEp/pages/_app.js:4170:198)
    at /Users/lucasfeliciano/Project/.next/server/static/3qDzHatrKal7YRNVFxVEp/pages/_app.js:4170:378
    at new Promise (<anonymous>)
    at Function.<anonymous> (/Users/lucasfeliciano/Project/.next/server/static/3qDzHatrKal7YRNVFxVEp/pages/_app.js:4170:101)
    at Function.getInitialProps (/Users/lucasfeliciano/Project/.next/server/static/3qDzHatrKal7YRNVFxVEp/pages/_app.js:4408:33)
    at Function._callee$ (/Users/lucasfeliciano/Project/.next/server/static/3qDzHatrKal7YRNVFxVEp/pages/_app.js:3162:30)
    at tryCatch (/Users/lucasfeliciano/Project/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/lucasfeliciano/Project/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/lucasfeliciano/Project/node_modules/regenerator-runtime/runtime.js:114:21)
/_next/webpack-hmr
```

I didn't know the reason so I had to investigate, starting from the error stack trace I went to

```
.next/server/static/3qDzHatrKal7YRNVFxVEp/pages/_app.js:4164:131
```

Which is: 

```
/* harmony import */ var date_fns_is_same_month__WEBPACK_IMPORTED_MODULE_2___default = /*#__PURE__*/__webpack_require__.n(date_fns_is_same_month__WEBPACK_IMPORTED_MODULE_2__)
```

So I went on the only place of our application where we import this module and commented it out:

![image](https://user-images.githubusercontent.com/968014/52068432-f3533600-257c-11e9-8aa6-d2e8322ba989.png)

By doing that the error was gone.

To be honest I have no idea what is the cause of it and I could use some help!

**Comment by kossnocorp** [comment]
You should import the function like you import others:

```js
import { isSameMonth } from 'date-fns/is_same_month'
// →
import isSameMonth from 'date-fns/is_same_month'
```

I'm not quite sure how it was working before, but I assume that the environment has changed (webpack/Babel version, set of plugins, etc.).
