### ISSUE TITLE
Npm install error

### ISSUE THREAD

**Issue by christopherbauer** [date-fns/date-fns#1132]
Deploying a react project with date-fns dependency on Ubuntu EC2 instance throws an exception:

> date-fns@2.0.0-alpha.27 postinstall /root/www/~proj/web/node_modules/date-fns
> node ./docs/printV2Notice.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/root/www/~proj/web/node_modules/date-fns/docs/printV2Notice.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

 Failed at the date-fns@2.0.0-alpha.27 postinstall script 'node ./docs/printV2Notice.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the date-fns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./docs/printV2Notice.js

**Comment by christopherbauer** [comment]
It appears the docs folder doesn't come down for some reason.
