### ISSUE TITLE
Inconsistency between typings, documentation and exporting

### ISSUE THREAD

**Issue by LinusU** [date-fns/date-fns#1281]
I'll use `differenceInHours` as an example here, since this is where I first noticed it.

The documentation says that this is the way to import the module using CommonJS (as is used by Node.js):

```js
var differenceInHours = require('date-fns/differenceInHours')
```

In TypeScript, this would be:

```ts
import differenceInHours = require('date-fns/differenceInHours')
```

However, the typings says that the modules are ES modules and that they export a `default` property, and thus should be imported with `import differenceInHours from 'date-fns/differenceInHours'` in TypeScript. There is no `default` property exported though:

```sh
$ node
> require('date-fns/differenceInHours').default
undefined
```

So lets look at the source:

```js
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = differenceInHours;

// ...

function differenceInHours(dirtyDateLeft, dirtyDateRight) {
  // ...
}

module.exports = exports.default;
```

So what happens here is that first `__esModule` and `default` are being set on the `export` object. But at the last line in the file, the entire export object is being replaced by `exports.default`, a.k.a. `differenceInHours`.

In effect, it would behave exactly the same if the file were just:

```js
function differenceInHours(dirtyDateLeft, dirtyDateRight) {
  // ...
}

module.exports = differenceInHours;
```

-----

In the end I'm getting the following error when trying to use it in TypeScript:

```text
TypeError: differenceInHours_1.default is not a function
    at Object.<anonymous> (/private/tmp/hjdais/index.js:4:40)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11
```

-----

Unfortunately, TypeScript doesn't currently allow a module to be declared as being both compatible with CommonJS and ESM, so I don't think that I will be able to use the `import _ = require(_)` syntax without us breaking the `import _ from _` syntax...

That being said, I think that the best way forward is the make sure that the modules are exported something like this:

```js
function differenceInHours(dirtyDateLeft, dirtyDateRight) {
  // ...
}

Object.defineProperty(differenceInHours, "__esModule", {
  value: true
});

differenceInHours.default = differenceInHours;

module.exports = differenceInHours;
```

**Comment by LinusU** [comment]
To elaborate a bit on the difference between the two TypeScript syntaxes:

`import _ = require('...')`

This style compiles down to `const _ = require('...')`. In order to import a module like this, the type definitions must use the `export = ...` syntax to declare the exported value.

`import _ from '...'`

This style compiles down to `const _ = require('...').default`. In order to import a module like this, the type definitions must use the `export default ...` syntax to declare the exported value.

-----

The best practice (how DefinitelyTyped does it) is that if the source code uses `module.exports = ...`, it should be typed using `export = _`, and if the source code uses `exports.default = ...` it should be typed using `export default ...`.

In this case though, it seems like you want to do both at the same time, and TypeScript doesn't allow both styles to be present in the same file.

This is unfortunate because, in my opinion, until Node.js gets native module support, CommonJS is the system that is being used. So when writing TypeScript code for Node.js & CommonJS, it's very nice to use the `import _ = require('...')` syntax, since that matches the output code and works perfectly with all current Node.js modules...

**Comment by kossnocorp** [comment]
@LinusU thank you a lot for the issue, your explanation of the problem and proposed solution are excellent 🙏

**Comment by kossnocorp** [comment]
During the research, I found that the solution to your problem breaks a more common case when EcmaScript Modules are used without `esModuleInterop` set to `true`. 

See the issue and following PR:

- https://github.com/date-fns/date-fns/issues/1128
- https://github.com/date-fns/date-fns/pull/1180

I don't see a simple solution, except that we could special alias definitions in `date-fns/cjs`, i.e:

```ts
import differenceInHours1 from 'date-fns/differenceInHours'
import differenceInHours2 = require('date-fns/cjs/differenceInHours')
```

**Comment by LinusU** [comment]
Just wanted you to know that this is still present, and it's quite annoying when using date-fns in a pure Node.js project when using VS Code.

<img width="530" alt="Screenshot 2020-01-17 at 14 25 34" src="https://user-images.githubusercontent.com/189580/72619459-3ac10680-3935-11ea-820a-5fad6f5ffbf1.png">

Note that this is not a TypeScript file, just a normal JavaScript file. So I cannot work around this by switching to `import _ from _` since Node.js LTS doesn't support that...

I think a really nice workaround would be if we also set `.default` on the exported functions, that way they can be imported like this: (which is quite normal for other packages that have moved to ES modules)

<img width="401" alt="Screenshot 2020-01-17 at 14 27 18" src="https://user-images.githubusercontent.com/189580/72619567-7956c100-3935-11ea-95df-e6a1146286e6.png">

Note that this currently **does not** trigger an error, even though `startOfToday` will actually be `undefined` if you try and run the script...

-----

Note that the code today actually tries to set `exports.default`, but then overwrites it later in the file:

<img width="640" alt="Screenshot 2020-01-17 at 14 29 10" src="https://user-images.githubusercontent.com/189580/72619684-c0dd4d00-3935-11ea-89c3-3699942f3cbd.png">

<img width="443" alt="Screenshot 2020-01-17 at 14 29 16" src="https://user-images.githubusercontent.com/189580/72619694-c63a9780-3935-11ea-8f08-e9910f1bca67.png">

If this could just be changed to something like this I would be so happy:

```js
// ...
function startOfToday() {
  return (0, _index.default)(Date.now());
}

Object.defineProperty(startOfToday, "__esModule", {
  value: true
});
startOfToday.default = startOfToday;
module.exports = startOfToday;
```

**Comment by LinusU** [comment]
btw. the change I outlined above should make it work both with or without `esModuleInterop`. It also shouldn't affect any current usage, since the TypeScript definitions will stay exactly the same, and since the function will still be assigned to `module.exports`.

**Comment by techieshark** [comment]
For the benefit of search engines, adding the specific error messages I'm seeing in JS code that I'm working on updating to TS (similar error as @LinusU shared as a screenshot):

```
error TS2349: This expression is not callable.
  Type 'typeof import("date-fns/subSeconds")' has no call signatures.
  Type 'typeof import("date-fns/add")' has no call signatures.
  Type 'typeof import("date-fns/isValid")' has no call signatures.
  Type 'typeof import("date-fns/fromUnixTime")' has no call signatures.
```

for code like:
```
// myfile.js
const subSeconds = require('date-fns/subSeconds');
const fromUnixTime = require('date-fns/fromUnixTime');
// etc
```

**Comment by TheSolidForge** [comment]
i stumbled onto this today with Node.js 14 i think - i'm learning this still. to add my experience and fix to what exactly was happening to me, but this time it was with: formatDistanceToNowStrict 

This was initially causing the problem: 
```
import formatDistanceToNowStrict from "date-fns/formatDistanceToNowStrict";

function distanceToNow(dateTime: number | Date) {
  return (
    formatDistanceToNowStrict(dateTime, {
      addSuffix: true,
    })
  );
}
```

Build error: 
Type error: This expression is not callable.
  Type 'typeof import("/***/***/date-fns/formatDistanceToNowStrict")' has no call signatures.

   7 |
   8 | function distanceToNow(dateTime: number | Date) {
>  9 |   return formatDistanceToNowStrict(dateTime, {
     |          ^
  10 |     addSuffix: true,
  11 |   });
  12 | }

to fix this, change the import to have { }:

`import {formatDistanceToNowStrict} from "date-fns/formatDistanceToNowStrict";`
