### ISSUE TITLE
ES6 import doesn't work in node.js

### ISSUE THREAD

**Issue by PazzaVlad** [date-fns/date-fns#1282]
Hi!

I try to use date-fns (2.0.0-beta.4) in node 12.7.0 with '--experimental-modules' enabled. Mac OS 10.14.

**This works perfectly fine:**
```js
import _ from 'lodash'
import dateFns from 'date-fns'
```

**but none of these work:** 
```js
import { format } from 'date-fns'
```
It will throw error:

```
file:///Users/vlad/Documents/Projects/Sanbox/pure-sandbox/date-fns.mjs:4
import { format } from 'date-fns'
         ^^^^^^
SyntaxError: The requested module 'date-fns' does not provide an export named 'format'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:93:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:108:20)
    at async Loader.import (internal/modules/esm/loader.js:134:24)
[nodemon] app crashed - waiting for file changes before starting...
```

```js
import fnsLocaleRu from 'date-fns/locale/ru'
```
```
internal/modules/esm/default_resolve.js:59
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module '/Users/vlad/Documents/Projects/Sanbox/pure-sandbox/node_modules/date-fns/locale/ru' imported from /Users/vlad/Documents/Projects/Sanbox/pure-sandbox/date-fns.mjs
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:59:13)
    at Loader.resolve (internal/modules/esm/loader.js:73:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:149:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:43:40)
    at link (internal/modules/esm/module_job.js:42:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

```js
import { ru } from 'date-fns/locale'
```
```
internal/modules/esm/default_resolve.js:59
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module '/Users/vlad/Documents/Projects/Sanbox/pure-sandbox/node_modules/date-fns/locale' imported from /Users/vlad/Documents/Projects/Sanbox/pure-sandbox/date-fns.mjs
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:59:13)
    at Loader.resolve (internal/modules/esm/loader.js:73:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:149:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:43:40)
    at link (internal/modules/esm/module_job.js:42:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by TrySound** [comment]
experimental-modules are not ready to use. They are changed and may be changed again. It's better to use something less opinionated like https://github.com/standard-things/esm

**Comment by PazzaVlad** [comment]
@TrySound yeah, but other 20+ modules works well, so I thought maybe it's problem with date-fns

**Comment by TrySound** [comment]
This package ship modules via module field which is not supported by node modules. mjs does not work well with webpack.

**Comment by PazzaVlad** [comment]
Thanks
Renaming extension to 'js' and using esm (node -r esm date-fns.js) solve the problem. With mjs named export doesn't work.

**Comment by kossnocorp** [comment]
@TrySound thank you for chiming in!

Closing as there's nothing actionable atm (?).

**Comment by TrevTheDev** [comment]
@kossnocorp  - I have the same problem.  It seems like date-fns is not playing nice with node modules.

**Comment by vitaliytv** [comment]
```
import fns from 'date-fns'
const { format } = fns
```

**Comment by ryanfiller** [comment]
> ```
> import fns from 'date-fns'
> const { format } = fns
> ```

Curious how well this code splits? This will import all of `fns`, right?

**Comment by kossnocorp** [comment]
@ryanfiller yes, the way to activate tree-shaking would be to do like that:

```js
export { format } from 'date-fns'
```

But as I understand, this issue is about ESM in Node.js, and there tree-shaking doesn't make any sense. 

Regarding ESM in Node.js, it's coming in v3.
