### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by mdelclaro** [date-fns/date-fns#1308]
I'm getting this error when executing my project after adding the library:

```
export { default as addBusinessDays } from './addBusinessDays/index.js';
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.newLoader [as .js] (/home/mdelclaro/Misc/Bootcamp/goBarber/backend/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/mdelclaro/Misc/Bootcamp/goBarber/backend/src/app/controllers/Appointment.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module._compile (/home/mdelclaro/Misc/Bootcamp/goBarber/backend/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.newLoader [as .js] (/home/mdelclaro/Misc/Bootcamp/goBarber/backend/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/mdelclaro/Misc/Bootcamp/goBarber/backend/src/routes.js:9:20)
```

**Comment by mdelclaro** [comment]
Sorry, I just realized that VS Code had auto-imported it from the wrong place:

```js
import { isBefore } from 'date-fns/esm';
```
Instead of:
```js
import { isBefore } from 'date-fns';
```

**Comment by ctsstc** [comment]
I was afraid I was going to have to do some janky next js hack/client-side-only shenanigan, thank gort < 3.

**Comment by jobajuba** [comment]
> Sorry, I just realized that VS Code had auto-imported it from the wrong place:
> 
> ```js
> import { isBefore } from 'date-fns/esm';
> ```
> 
> Instead of:
> 
> ```js
> import { isBefore } from 'date-fns';
> ```

Took a while to realise this. Glad I ran into this page. Thanks
