### ISSUE TITLE
syntax error running build

### ISSUE THREAD

**Issue by redbugz** [date-fns/date-fns#1528]
When running  a build:
`./scripts/build/build.sh` I am getting this syntax error:

```
./scripts/build/build.sh 
+ ./scripts/build/docs.js
+ ./scripts/build/fp.js
+ ./scripts/build/typings.js
/Users/redbugz/dev/tools/date-fns/node_modules/prettier/index.js:10640
      throw error;
      ^

SyntaxError: '{' or ';' expected. (289:17)
  287 |       step?: number
  288 |     }
> 289 |   ): [ 'Array' ].<Date>
      |                 ^
  290 |   namespace eachDayOfInterval {}
  291 | 
  292 |   function eachWeekendOfInterval (
    at e (/Users/redbugz/dev/tools/date-fns/node_modules/prettier/parser-typescript.js:1:267)
    at Object.parse (/Users/redbugz/dev/tools/date-fns/node_modules/prettier/parser-typescript.js:1:2261711)
    at Object.parse$2 [as parse] (/Users/redbugz/dev/tools/date-fns/node_modules/prettier/index.js:10629:19)
    at coreFormat (/Users/redbugz/dev/tools/date-fns/node_modules/prettier/index.js:13888:23)
    at format (/Users/redbugz/dev/tools/date-fns/node_modules/prettier/index.js:14146:73)
    at formatWithCursor (/Users/redbugz/dev/tools/date-fns/node_modules/prettier/index.js:14162:12)
    at /Users/redbugz/dev/tools/date-fns/node_modules/prettier/index.js:42756:15
    at Object.format (/Users/redbugz/dev/tools/date-fns/node_modules/prettier/index.js:42775:12)
    at module.exports (/Users/redbugz/dev/tools/date-fns/scripts/build/_lib/prettier.js:5:19)
    at writeFile (/Users/redbugz/dev/tools/date-fns/scripts/build/_lib/typings/typeScript.js:446:5) {
  loc: { start: { line: 289, column: 17 } },
  codeFrame: '\u001b[0m \u001b[90m 287 | \u001b[39m      step\u001b[33m?\u001b[39m\u001b[33m:\u001b[39m number\u001b[0m\n' +
    '\u001b[0m \u001b[90m 288 | \u001b[39m    }\u001b[0m\n' +
    "\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 289 | \u001b[39m  )\u001b[33m:\u001b[39m [ \u001b[32m'Array'\u001b[39m ]\u001b[33m.\u001b[39m\u001b[33m<\u001b[39m\u001b[33mDate\u001b[39m\u001b[33m>\u001b[39m\u001b[0m\n" +
    '\u001b[0m \u001b[90m     | \u001b[39m                \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m 290 | \u001b[39m  namespace eachDayOfInterval {}\u001b[0m\n' +
    '\u001b[0m \u001b[90m 291 | \u001b[39m\u001b[0m\n' +
    '\u001b[0m \u001b[90m 292 | \u001b[39m  \u001b[36mfunction\u001b[39m eachWeekendOfInterval (\u001b[0m'
}
```
I'm not familiar enough with TS namespaces or how the typings are getting generated to understand this error. It certainly seems like `: [ 'Array' ].<Date>` is not a valid return type, but not sure why it's getting generated this way.

**Comment by dkozickis** [comment]
Hi @redbugz, what's your setup like? OS?

**Comment by redbugz** [comment]
MacOS Mojave 10.14.6, Node 12.13.0 installed via nvm, yarn 1.17.3 installed via homebrew, oh-my-zsh

**Comment by dkozickis** [comment]
I happen to have same issue on similar setup.
However, using either Node 8 or 10 works just fine.

I've narrowed it down a bit further - running `./scripts/build/docs.js` with Node v10 and then `./scripts/build/typings.js` with Node v12 works fine, so the issue seems to be how docs are build @ Node 12.

Long story short - seems that `jsdoc-to-markdown` needs a bump, as we're using own 3 years old fork, Node 12 wasn't out then :) 

JSDoc mentions support for Node 12 landed this May - https://github.com/jsdoc/jsdoc/blob/85581b8a84092faedc0b2028531374f41ee4ef2c/CHANGES.md#360-may-2019
