### ISSUE TITLE
Can't import ro locales

### ISSUE THREAD

**Issue by mihai-osvat** [date-fns/date-fns#1600]
Hi, I'm using version 2.9.0, and I'm importing:

`import { ro } from 'date-fns/locale';`

Everything works fine in development mode, but when I build for production, I get these errors:

`"export 'ro' (imported as 'i19') was not found in 'date-fns'
    at HarmonyImportSpecifierDependency._getErrors (D:\@Work\NodeJs\nl-techup\uBid\uBid-App\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:109:11)
    at HarmonyImportSpecifierDependency.getErrors (D:\@Work\NodeJs\nl-techup\uBid\uBid-App\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (D:\@Work\NodeJs\nl-techup\uBid\uBid-App\node_modules\webpack\lib\Compilation.js:1425:22)
    at hooks.finishModules.callAsync.err (D:\@Work\NodeJs\nl-techup\uBid\uBid-App\node_modules\webpack\lib\Compilation.js:1221:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\@Work\NodeJs\nl-techup\uBid\uBid-App\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:42:1)
    at AsyncSeriesHook.lazyCompileHook (D:\@Work\NodeJs\nl-techup\uBid\uBid-App\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (D:\@Work\NodeJs\nl-techup\uBid\uBid-App\node_modules\webpack\lib\Compilation.js:1216:28)
    at hooks.make.callAsync.err (D:\@Work\NodeJs\nl-techup\uBid\uBid-App\node_modules\webpack\lib\Compiler.js:662:17)
    at _done (eval at create (D:\@Work\NodeJs\nl-techup\uBid\uBid-App\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at _err4 (eval at create (D:\@Work\NodeJs\nl-techup\uBid\uBid-App\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:72:22)
    at _addModuleChain (D:\@Work\NodeJs\nl-techup\uBid\uBid-App\node_modules\webpack\lib\Compilation.js:1148:12)
    at processModuleDependencies.err (D:\@Work\NodeJs\nl-techup\uBid\uBid-App\node_modules\webpack\lib\Compilation.js:1060:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)`

I took a look inside the node_modules, and I was able to find the /locale/ro folder within the 'date-fns'.

**Comment by mihai-osvat** [comment]
Hi, anything new on the matter ?

**Comment by csi0n** [comment]
I have the same problem. How can I solve it?

**Comment by csi0n** [comment]
@mihai-osvat

**Comment by csi0n** [comment]
@mihai-osvat 
I know how to solve this problem
just change 
```
import { ro } from 'date-fns/locale';
```
to
```
import * as ro from 'date-fns/locale/ro/index.js';
```

**Comment by mihai-osvat** [comment]
> @mihai-osvat
> I know how to solve this problem
> just change
> 
> ```
> import { ro } from 'date-fns/locale';
> ```
> 
> to
> 
> ```
> import * as ro from 'date-fns/locale/ro/index.js';
> ```

Will try, thanks !

**Comment by mihai-osvat** [comment]
> @mihai-osvat
> I know how to solve this problem
> just change
> 
> ```
> import { ro } from 'date-fns/locale';
> ```
> 
> to
> 
> ```
> import * as ro from 'date-fns/locale/ro/index.js';
> ```

Yes, I can confirm that your solution works on production build. Many thanks and kind regards !
