### ISSUE TITLE
ES import 'date-fns/fp' fails on Node 14

### ISSUE THREAD

**Issue by alexbepple** [date-fns/date-fns#1779]
```js
import { addDays } from 'date-fns/fp'
```

fails with 

```
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/.../temp/node_modules/date-fns/fp' imported from /.../temp/date-fns-test.mjs
Did you mean to import date-fns/fp/index.js?
    at finalizeResolution (internal/modules/esm/resolve.js:277:11)
    at packageResolve (internal/modules/esm/resolve.js:608:14)
    at moduleResolve (internal/modules/esm/resolve.js:655:14)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:748:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
    at link (internal/modules/esm/module_job.js:41:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Tried this on both Node 14.0 and 14.2. Also with both date-fns 2.12 and 2.13.

**Comment by kossnocorp** [comment]
Sadly right now date-fns doesn't support Node.js ESM. To add it we need to introduce a breaking change, so I've created a separate issue for that: https://github.com/date-fns/date-fns/issues/1781
