### ISSUE TITLE
Error while Testing using babel-node

### ISSUE THREAD

**Issue by aryanshridhar** [date-fns/date-fns#1973]
While executing <code>> const toDate = require('./src/toDate')</code> after <code>./node_modules/.bin/babel-node</code> throws an error as : 
<pre>
 const toDate = require('./src/toDate')
internal/modules/cjs/loader.js:968
  throw err;
  ^

Uncaught Error: Cannot find module '../_lib/requiredArgs/index'
Require stack:
- /home/aryanshridhar/Desktop/date-fns/src/toDate/index.js
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/aryanshridhar/Desktop/date-fns/src/toDate/index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module._compile (/home/aryanshridhar/Desktop/date-fns/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.newLoader [as .js] (/home/aryanshridhar/Desktop/date-fns/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:985:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/aryanshridhar/Desktop/date-fns/src/toDate/index.js',
    '<repl>'
  ]
}
</pre>

Am I missing out something ?

**Comment by fturmel** [comment]
To use the REPL, try invoking `babel-node` like this instead or it won't transpile TypeScript files: `yarn babel-node -x .ts,.js`

<img width="679" alt="Screen Shot 2021-12-18 at 7 04 05 PM" src="https://user-images.githubusercontent.com/4009209/146658832-c37c1903-1164-45a0-ae86-b84cd50a2e41.png">
