### ISSUE TITLE
Show warning message only once or disable

### ISSUE THREAD

**Issue by basickarl** [date-fns/date-fns#2271]
Can yous please refrain from adding the warning message EVERY time the date fns is used. Once is enough. Or, how does one disable these messages:

```
Starting with v2.0.0-beta.1 date-fns doesn't accept strings as date arguments. Please use `parseISO` to parse strings. See: https://git.io/fjule
Error: 
    at toDate (/home/karl/dev/afry/tmr-gateway/node_modules/date-fns/toDate/index.js:56:20)
    at Object.compareAsc (/home/karl/dev/afry/tmr-gateway/node_modules/date-fns/compareAsc/index.js:52:37)
    at getAccessToken (/home/karl/dev/afry/tmr-gateway/src/bjornLunden.ts:324:35)
    at request (/home/karl/dev/afry/tmr-gateway/src/bjornLunden.ts:355:31)
    at putRequest (/home/karl/dev/afry/tmr-gateway/src/bjornLunden.ts:372:12)
    at Object.updateBlCustomer (/home/karl/dev/afry/tmr-gateway/src/bjornLunden.ts:403:24)
    at /home/karl/dev/afry/tmr-gateway/example/example_bl.ts:302:50
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

Completely screwed up the readability of all of our logging now.

**Comment by aaronparres** [comment]
Same problem here :(

**Comment by Darkmift** [comment]
any update on this?
