### ISSUE TITLE
Date.UTC is not a function

### ISSUE THREAD

**Issue by mdgeek** [date-fns/date-fns#2294]
Seeing this on unit tests with latest version (2.19.0).

**Comment by samueldjones24** [comment]
Same - pinned version to `2.18` for now

**Comment by matthoffner** [comment]
Seems to be specific to IE11 from my testing.

**Comment by tan75** [comment]
hi @mdgeek @frederikvanhevel @samueldjones24 
could you please provide more info as I don't see any tests failing.

**Comment by mdgeek** [comment]
Sorry, I should have been clearer.  I'm referring to my unit tests, not yours.  Here is the stack trace:

      at getTimezoneOffsetInMilliseconds (node_modules/date-fns/_lib/getTimezoneOffsetInMilliseconds/index.js:20:31)
      at Object.format (node_modules/date-fns/format/index.js:398:44)
      at Function.format (lib/src/common/util/date.util.ts:108:32)
      at lib/src/common/util/date.util.spec.ts:121:30
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:407:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3765:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:167:47)
      at Object.wrappedFunc (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4250:34)

**Comment by mdgeek** [comment]
The error I am seeing is this:

    TypeError: Date.UTC is not a function

These same unit tests have worked on all previous versions.

**Comment by mdgeek** [comment]
I just tried this with the latest release (2.20.1) with the same result.

**Comment by maximecote57** [comment]
This seems caused by the latest changes in `getTimezoneOffsetInMilliseconds` which now uses `Date.UTC`.

In my case I was mocking the `Date` object in my test, loosing that `UTC` property. You need to add it to your mocked `Date` object.

Rough example:

```
const oldGlobalDate = global.Date;

 beforeEach(() => {
    global.Date = jest.fn(() => 'some date');
    global.Date.UTC = oldGlobalDate.UTC;
  });
```

**Comment by mdgeek** [comment]
That is exactly it.  Thanks @maximecote57.

**Comment by decebal** [comment]
> This seems caused by the latest changes in `getTimezoneOffsetInMilliseconds` which now uses `Date.UTC`.
> 
> In my case I was mocking the `Date` object in my test, loosing that `UTC` property. You need to add it to your mocked `Date` object.
> 
> Rough example:
> 
> ```
> const oldGlobalDate = global.Date;
> 
>  beforeEach(() => {
>     global.Date = jest.fn(() => 'some date');
>     global.Date.UTC = oldGlobalDate.UTC;
>   });
> ```
Using this example causes yet another issue: `TypeError: argument.getTime is not a function` 😮‍💨 , might be unrelated though.

Something that I found to be very useful: https://codewithhugo.com/mocking-the-current-date-in-jest-tests/

So I went with:
```
 beforeEach(() => {
    jest.spyOn(global, 'Date')
      .mockImplementationOnce(() => new Date('2021-09-12T11:01:58.135Z'));
  });

```
