### ISSUE TITLE
typings build scripts failed

### ISSUE THREAD

**Issue by smmoosavi** [date-fns/date-fns#2473]
build script failed with this error. recently `src/constants/index.js` file are converted to `src/constants/index.ts` file (#2460)
```
./scripts/build/typings.js

/path-to-project/date-fns/node_modules/jsdoc-api/lib/explain-sync.js:8
    if (err) throw err
             ^

JSDOC_ERROR: These files do not exist: /path-to-project/date-fns/src/constants/index.js
    at ExplainSync.validate (/path-to-project/date-fns/node_modules/jsdoc-api/lib/jsdoc-command.js:86:19)
    at ExplainSync.execute (/path-to-project/date-fns/node_modules/jsdoc-api/lib/jsdoc-command.js:48:22)
    at Object.explainSync (/path-to-project/date-fns/node_modules/jsdoc-api/index.js:20:18)
    at JsdocToMarkdown.getJsdocDataSync (/path-to-project/date-fns/node_modules/jsdoc-to-markdown/index.js:131:21)
    at getConstants (/path-to-project/date-fns/scripts/_lib/getConstants.js:8:6)
    at Object.<anonymous> (/path-to-project/date-fns/scripts/build/typings.js:26:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)

```

**Comment by rikkalo** [comment]
Hi
Thanks for the issue.
Before running ./scripts/build/typings.js you need to run ./scripts/build/docs.js to generate tmp / docs.json.

**Comment by fturmel** [comment]
Seems broken to me as well. `getConstants` is referencing a file that doesn't exist anymore https://github.com/date-fns/date-fns/blob/master/scripts/_lib/getConstants.js#L9

**Comment by fturmel** [comment]
@tan75 Unfortunately I think this issue needs to be reopened. For me at least, the`jsdoc-to-markdown` library is now choking on the TypeScript file.

I'm making progress on a fix but not quite there yet.

```
/Users/fturmel/Documents/projects/forks/date-fns/node_modules/jsdoc-api/lib/jsdoc-command.js:114
      throw err
      ^

JSDOC_ERROR: There are no input files to process.
    at ExplainSync.verifyOutput (/Users/fturmel/Documents/projects/forks/date-fns/node_modules/jsdoc-api/lib/jsdoc-command.js:112:19)
    at ExplainSync._runJsdoc (/Users/fturmel/Documents/projects/forks/date-fns/node_modules/jsdoc-api/lib/explain-sync.js:34:32)
    at ExplainSync.getOutput (/Users/fturmel/Documents/projects/forks/date-fns/node_modules/jsdoc-api/lib/explain-sync.js:17:19)
    at ExplainSync.execute (/Users/fturmel/Documents/projects/forks/date-fns/node_modules/jsdoc-api/lib/jsdoc-command.js:49:24)
    at Object.explainSync (/Users/fturmel/Documents/projects/forks/date-fns/node_modules/jsdoc-api/index.js:20:18)
    at JsdocToMarkdown.getJsdocDataSync (/Users/fturmel/Documents/projects/forks/date-fns/node_modules/jsdoc-to-markdown/index.js:131:21)
    at getConstants (/Users/fturmel/Documents/projects/forks/date-fns/scripts/_lib/getConstants.js:8:6)
    at Object.<anonymous> (/Users/fturmel/Documents/projects/forks/date-fns/scripts/build/typings.js:26:19)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
```

**Comment by tan75** [comment]
@fturmel 
Yeah, didn't notice that - apologies! I will reopen and have a look as well.

**Comment by fturmel** [comment]
Alright, see PR #2488

There were two additional steps required:

1. Reference the jsdoc config file in the command so it can transpile with Babel
2. Add `@name` tags in the constants file. Without this the type annotations generated used the name `maxTime` for both constants somehow. Maybe the Babel output confused jsdoc because that was working before without `@name`.

**Comment by tan75** [comment]
@fturmel thank you so much for fixing this! Much appreciated!
I think I can close this issue now.
