### ISSUE TITLE
"Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by ybrodsky** [date-fns/date-fns#2655]
Nextjs 11
Webpack 5
Typescript 4.0.5

It appears that webpack 5 is the problem because with webpack 4 it does not happen. The full error:

```
error - unhandledRejection: /PATH/node_modules/date-fns/esm/format/index.js:1
import isValid from "../isValid/index.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Module._compile (/mnt/fc80ef5e-f0bf-400a-a4ff-0cb66da1654c/dev/nextjs-frontend/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .js] (/mnt/fc80ef5e-f0bf-400a-a4ff-0cb66da1654c/dev/nextjs-frontend/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.date-fns/esm/format (/mnt/fc80ef5e-f0bf-400a-a4ff-0cb66da1654c/dev/nextjs-frontend/.next/server/pages/_app.js:1868:18)
    ```

Any ideas?

**Comment by tan75** [comment]
hi @ybrodsky 
Which version of date-fns are you using?

**Comment by ybrodsky** [comment]
Hey,
I am using the latest version today

**Comment by ybrodsky** [comment]
Any idea?

**Comment by ybrodsky** [comment]
Found out the problem was with `date-fns-tz`. https://github.com/marnusw/date-fns-tz

Apologies.

**Comment by undsoft** [comment]
@ybrodsky Did you by any chance manage to find a solution to this issue?

**Comment by ybrodsky** [comment]
@undsoft as my previous comment the problem is the other module, date-fn-tz
You have to change the way you import that one.
