### ISSUE TITLE
Node16/Docker: Uncaught (in promise) RangeError: locale must contain formatDistance property

### ISSUE THREAD

**Issue by faulander** [date-fns/date-fns#2966]
The Code lives in a SvelteKit App which works fine on DEV. When i deploy it to node, i get the above error:
```
Uncaught (in promise) RangeError: locale must contain formatDistance property
    at Uk (vendor-3fe99b41.js:10:74337)
    at Array.a (moral.svelte-9f6f6e6f.js:1:8730)
    at $ (moral.svelte-9f6f6e6f.js:1:1376)
    at ut (moral.svelte-9f6f6e6f.js:1:6610)
    at Mt (vendor-3fe99b41.js:4:5064)
    at new _t (moral.svelte-9f6f6e6f.js:1:9350)
    at Object.p (start-4198a866.js:1:2751)
    at Object.p (start-4198a866.js:1:4384)
    at xr (vendor-3fe99b41.js:1:1594)
    at Object.p (__layout.svelte-9d364806.js:1:4047)
Uk @ vendor-3fe99b41.js:10
a @ moral.svelte-9f6f6e6f.js:1
$ @ moral.svelte-9f6f6e6f.js:1
ut @ moral.svelte-9f6f6e6f.js:1
Mt @ vendor-3fe99b41.js:4
_t @ moral.svelte-9f6f6e6f.js:1
p @ start-4198a866.js:1
p @ start-4198a866.js:1
xr @ vendor-3fe99b41.js:1
p @ __layout.svelte-9d364806.js:1
p @ __layout.svelte-9d364806.js:1
zx @ vendor-3fe99b41.js:4
my @ vendor-3fe99b41.js:4
Promise.then (asynchron)
fy @ vendor-3fe99b41.js:4
Ix @ vendor-3fe99b41.js:4
(anonym) @ vendor-3fe99b41.js:4
Je.i.$$set @ start-4198a866.js:1
$set @ vendor-3fe99b41.js:4
update @ start-4198a866.js:1
await in update (asynchron)
handle_navigation @ start-4198a866.js:1
_navigate @ start-4198a866.js:1
(anonym) @ start-4198a866.js:1
```

The code:
```
    import {  formatDistance, format, parseISO } from 'date-fns'
    //import de from 'date-fns/locale/index.js'
    
    //const duration = s => formatDistance(0, s * 1000, {includeSeconds: true, locale: de})
    const duration = s => formatDistance(0, s * 1000, {includeSeconds: true})
```

**Comment by fturmel** [comment]
The locale import is wrong. `de` will be `undefined` because there are no default exports in the index.

In your dev environment, it was probably just defaulting to `en-US` instead of `de`. Maybe the prod build outputs different JS code (transpiler, optimizations) that exposed the mistake in a more obvious way.

Try any of these instead:

Import through the locale index, which exposes `de` as a named export:
```js
import { de } from "date-fns/locale";
import { de } from "date-fns/locale/index";
import { de } from "date-fns/locale/index.js";
```

Import the locale file directly, which has a default export:
```js
import de from "date-fns/locale/de";
import de from "date-fns/locale/de/index";
import de from "date-fns/locale/de/index.js";
```

If somehow this doesn't work, you can also try to explicitly load from the `esm` directory:

```js
import { de } from "date-fns/esm/locale";
import { de } from "date-fns/esm/locale/index";
import { de } from "date-fns/esm/locale/index.js";

import de from "date-fns/esm/locale/de";
import de from "date-fns/esm/locale/de/index";
import de from "date-fns/esm/locale/de/index.js";
```
