### ISSUE TITLE
MODULE_NOT_FOUND. Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by mo4islona** [date-fns/date-fns#3413]
The latest release seems missing a main file 

test.ts
```ts
import { compareAsc, format } from 'date-fns';

format(new Date(2014, 1, 11), 'yyyy-MM-dd');
//=> '2014-02-11'

const dates = [new Date(1995, 6, 2), new Date(1987, 1, 11), new Date(1989, 6, 10)];
dates.sort(compareAsc);
```

package.json
```json
{
  "dependencies": {
    "date-fns": "^2.30.0"
  }
}
```

```ts-node test.ts
Error: Cannot find module '/Users/mo4islona/Projects/test/node_modules/date-fns/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:436:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:678:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/opt/homebrew/lib/node_modules/ts-node/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/mo4islona/Projects/test/test.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (/opt/homebrew/lib/node_modules/ts-node/src/index.ts:1618:23) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/mo4islona/Projects/test/node_modules/date-fns/package.json',
  requestPath: 'date-fns'
}
```

Works fine if downgrade to
``` json
{
    "dependencies": {
      "date-fns": "2.29.3"
    }
  }
```

**Comment by mo4islona** [comment]
Definitely related  to https://github.com/date-fns/date-fns/issues/3208
