### ISSUE TITLE
addWeeks and subWeeks not importing correctly in React App 

### ISSUE THREAD

**Issue by anissalopez** [date-fns/date-fns#3493]
Hi, 

I have installed date-fns into my react app, and I am able to correctly use some of the functions, but addWeeks and subWeeks is not importing correctly. Any help would be greatly appreciated!

**Comment by dshubhadeep** [comment]
@anissalopez could you provide a code sample & the error message that you are getting?

**Comment by dmlb** [comment]
Seeing a possibly similar type error related to subweeks

```
date-fns ^4.0.0
node 22.12.0
```


```
const subWeeks = require('date-fns/subWeeks');
const oneWeekAgo = subWeeks(now, 1).toISOString();
```


```
TypeError: subWeeks is not a function
    at Object.main [as generate] (/home/runner/work/scripts/metrics/deployment-frequency.js:19:21)
    at main (/home/runner/work/scripts/metrics/generate-metrics.js:20:24)
    at Object.<anonymous> (/home/runner/work/scripts/metrics/generate-metrics.js:125:1)
    at Module._compile (node:internal/modules/cjs/loader:1554:14)
    at Object..js (node:internal/modules/cjs/loader:1706:10)
    at Module.load (node:internal/modules/cjs/loader:1289:32)
    at Function._load (node:internal/modules/cjs/loader:1108:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
```
