### ISSUE TITLE
Not working on Edge Workers (e.g. Vercel Edge Functions, Cloudflare Workers)

### ISSUE THREAD

**Issue by MickL** [date-fns/date-fns#3576]
It seems like date-fns is not working on Edge Workers that dont have the full Node API. Could it be that date-fns uses functions that are [not supported](https://vercel.com/docs/functions/edge-functions/edge-runtime)?

Error on Vercel Edge Functions:
> TypeError: t is not a function
>     at (index.mjs:1:110837)
>     at (index.mjs:1:110877)
>     at (__nitro:middleware.js:1:17)

Error on Cloudflare Workers:

> Error: Failed to publish your Function. Got error: Uncaught TypeError: r2 is not a function 
>    at functionsWorker-0.5884842512200903.js:3588:12
>    at functionsWorker-0.5884842512200903.js:3590:2

**Comment by MickL** [comment]
Seems to be because of this issue from 2020: https://github.com/date-fns/date-fns/issues/1781
Issue on side of Nitro: https://github.com/unjs/nitro/issues/1889
