### ISSUE TITLE
v2 Documentation throws JSON parse error

### ISSUE THREAD

**Issue by Ponjimon** [date-fns/date-fns#3611]
When selecting any other version than the newly released 3.0.0 in the documentation, I get this in the console and the page just says "Loading..."

```
index.js:10 Uncaught SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at parse (index.js:10:1)
    at d.Content [as constructor] (Content.tsx:18:31)
    at d.O [as render] (preact.module.js:1:8222)
    at j (preact.module.js:1:5904)
    at w (preact.module.js:1:2149)
    at L (preact.module.js:1:7384)
    at j (preact.module.js:1:6315)
    at w (preact.module.js:1:2149)
    at j (preact.module.js:1:6042)
    at w (preact.module.js:1:2149)
    at L (preact.module.js:1:7384)
    at j (preact.module.js:1:6315)
    at w (preact.module.js:1:2149)
    at j (preact.module.js:1:6042)
    at w (preact.module.js:1:2149)
    at j (preact.module.js:1:6042)
    at preact.module.js:1:1484
    at Array.some (<anonymous>)
    at g (preact.module.js:1:1390)
    at sentryWrapped (helpers.js:72:1)
    ```

**Comment by ivan-zakharchuk** [comment]
see the same issue, it incredibly that nobody is testing that website

**Comment by kossnocorp** [comment]
Thank you for the report. I need more info. Browser, OS, versions, can you reproduce in another browser? Can you reproduce it on mobile? Steps to reproduce?

**Comment by kossnocorp** [comment]
@sberryman no, I did not see it following the original instructions. Having a URL, at least, helped to solve the problem. Thanks
