### ISSUE TITLE
After updating to v.3 MUI AdapterDateFns can't find the export

### ISSUE THREAD

**Issue by matveychuk** [date-fns/date-fns#3638]
After updating to v.3 MUI AdapterDateFns can't find the export

MUI versions:
    "@mui/base": "^5.0.0-beta.29",
    "@mui/icons-material": "^5.15.2",
    "@mui/lab": "^5.0.0-alpha.158",
    "@mui/material": "^5.15.2",
    "@mui/x-date-pickers": "^6.18.6",
date-fns version:
    "date-fns": "^3.0.6",

Module not found: Error: Package path ./_lib/format/longFormatters is not exported from package .../node_modules/date-fns (see exports field in .../node_modules/date-fns/package.json)
ERROR in ../../node_modules/@mui/x-date-pickers/AdapterDateFns/AdapterDateFns.js 59:0-65

With version 2.27.0 it works normally.

**Comment by aemonm** [comment]
Same issue. Really looking forward to having easier ways of working with UTC dates in date-fns v3, but we currently depend on mui for our date-pickers so we won't be able to upgrade until this is resolved.

**Comment by humarkx** [comment]
```✘ [ERROR] Missing "./_lib/format/longFormatters" specifier in "date-fns" package [plugin vite:dep-pre-bundle]

    node_modules/vite/node_modules/esbuild/lib/main.js:1373:21:
      1373 │         let result = await callback({
           ╵                      ^

    at e (file:///Users/u/projects/r/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:21914:25)
    at n (file:///Users/u/projects/r/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:21914:627)
    at o (file:///Users/u/projects/r/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:21914:1297)
    at resolveExportsOrImports (file:///Users/u/projects/r/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:29473:20)
    at resolveDeepImport (file:///Users/u/projects/r/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:29492:31)
    at tryNodeResolve (file:///Users/u/projects/r/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:29217:20)
    at Context.resolveId (file:///Users/u/projects/r/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:28985:28)
    at Object.resolveId (file:///Users/u/projects/r/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:63629:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/u/projects/r/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:67637:21
    at async file:///Users/u/projects/r/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:41080:34
    at async requestCallbacks.on-resolve (/Users/u/projects/r/webapp/node_modules/vite/node_modules/esbuild/lib/main.js:1373:22)
    at async handleRequest (/Users/u/projects/r/webapp/node_modules/vite/node_modules/esbuild/lib/main.js:731:11)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/u/projects/r/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:41060:19)
    at handlePlugins (/Users/u/projects/r/webapp/node_modules/vite/node_modules/esbuild/lib/main.js:1292:21)
    at buildOrContextImpl (/Users/u/projects/r/webapp/node_modules/vite/node_modules/esbuild/lib/main.js:978:5)
    at Object.buildOrContext (/Users/u/projects/r/webapp/node_modules/vite/node_modules/esbuild/lib/main.js:787:5)
    at /Users/u/projects/r/webapp/node_modules/vite/node_modules/esbuild/lib/main.js:2207:68
    at new Promise (<anonymous>)
    at Object.context (/Users/u/projects/r/webapp/node_modules/vite/node_modules/esbuild/lib/main.js:2207:27)
    at Object.context (/Users/u/projects/r/webapp/node_modules/vite/node_modules/esbuild/lib/main.js:2047:58)
    at prepareEsbuildOptimizerRun (file:///Users/u/projects/r/webapp/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:65419:35)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/@mui/x-date-pickers/AdapterDateFns/AdapterDateFns.js:59:27:
      59 │ import longFormatters from 'date-fns/_lib/format/longFormatters';
         ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/Users/u/projects/r/webapp/node_modules/vite/node_modules/esbuild/lib/main.js:1650
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
node_modules/vite/node_modules/esbuild/lib/main.js:1373:21: ERROR: [plugin: vite:dep-pre-bundle] Missing "./_lib/format/longFormatters" specifier in "date-fns" package
    at failureErrorWithLog (/Users/u/projects/r/webapp/node_modules/vite/node_modules/esbuild/lib/main.js:1650:15)
    at /Users/u/projects/u/webapp/node_modules/vite/node_modules/esbuild/lib/main.js:1058:25
    at /Users/u/projects/u/webapp/node_modules/vite/node_modules/esbuild/lib/main.js:1526:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}```

**Comment by kossnocorp** [comment]
Hey, this is an issue with MUI incompatible with the new version please follow the progress here: https://github.com/mui/mui-x/issues/11454

**Comment by kossnocorp** [comment]
Sure, I can add exports to internals. Let me think about how to approach it, and I'll get back to you.

**Comment by kossnocorp** [comment]
@LukasTy so, the next version will export internals from `format`, `lightFormat`, and `parse`: https://github.com/date-fns/date-fns/commit/3d85c7df7f25267e4774103addd773d99b455edb

This provides transparency to whoever changes those that they are part of public API. If I were to add exports to those files directly, I wouldn't be able to update the file structure anymore.

I'm not sure if it's what you expected, given there's no backward compatibility. If not, let's discuss the options we have.

**Comment by kossnocorp** [comment]
Shipped with https://github.com/date-fns/date-fns/releases/tag/v3.2.0

**Comment by LukasTy** [comment]
Thank you, @kossnocorp, for a very quick solution! 🙏 
It seems to work brilliantly. 👍 
We were able to use the now exported `longFormatters` (https://github.com/mui/mui-x/pull/11462/commits/b6c92dfbd086d44b99358300c417ee5875ad343b) to successfully support date-fns@v3.

> I'm not sure if it's what you expected, given there's no backward compatibility. If not, let's discuss the options we have.

Well, it's always nice to avoid BCs, but understandably they are unavoidable, especially if we want less bloat. 👍 
We'll have to adapt if it is unavoidable. 👌

**Comment by kossnocorp** [comment]
@LukasTy perfect! Let me know if I can help further with the adapter. I'm planning v4 and can try to address any needs. Cheers!

**Comment by LukasTy** [comment]
> Let me know if I can help further with the adapter. I'm planning v4 and can try to address any needs. Cheers!

@kossnocorp feel free to reach out in any way you want if you will see that some breaking changes will be inevitable in v4. 😉

**Comment by kurpav** [comment]
Still the case for me

**Comment by shunyun-bp** [comment]
Any idea when this will be available? Currently still broken using date-fns 3.4.0 and mui/x-date-pickers-pro 6.19.7

**Comment by kossnocorp** [comment]
@shunyun-bp wrong place to ask, please see https://github.com/mui/mui-x

**Comment by LukasTy** [comment]
@shunyun-bp The support for `date-fns` v3 has been released in `@mui/x-date-pickers@6.19.0`.
You can find more information on how to use it [here](https://mui.com/x/react-date-pickers/adapters-locale/#with-date-fns).
If you still experience any problems, please feel free to open an issue in the respective repository. 🙏

**Comment by jafar-jabr** [comment]
don't know how this was closed, still the same issue with:
date-fns: 3.6.0
and
@mui/x-date-pickers: 7.2.0

**Comment by rupalchawla** [comment]
The solution is posted here 
https://github.com/mui/mui-x/issues/11454
 Replace AdapterDateFns with AdapterDateFnsV3

`- import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns';
+ import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFnsV3';`

**Comment by sshakil** [comment]
@mui/x-date-pickers": "^7.12.1", "date-fns": "^3.6.0", problem persists. may take a look soon

**Comment by LukasTy** [comment]
> @mui/x-date-pickers": "^7.12.1", "date-fns": "^3.6.0", problem persists. may take a look soon

What problem? 🤔 
Which adapter are you using?

**Comment by jakubjosef** [comment]
I had the same problem and updating my adapter to contain V3 in the end fixed the problem.
