### ISSUE TITLE
parse undefined breaking change

### ISSUE THREAD

**Issue by cheng93** [date-fns/date-fns#3645]
This returned `null` in 2.30.0, but is now throwing in 3.0.6 and was not documented. Is this an intended breaking change?

2.30.0 - https://stackblitz.com/edit/6rfqqh?file=index.ts
3.0.6 - https://stackblitz.com/edit/6rfqqh-gn1bzh?file=index.ts

```
TypeError: Cannot read properties of undefined (reading 'match')
    at parseNumericPattern (http://localhost:9876/_karma_webpack_/webpack:/node_modules/date-fns/parse/_lib/utils.mjs:20:34)
    at parseNDigits (http://localhost:9876/_karma_webpack_/webpack:/node_modules/date-fns/parse/_lib/utils.mjs:75:14)
    at YearParser.parse (http://localhost:9876/_karma_webpack_/webpack:/node_modules/date-fns/parse/_lib/parsers/YearParser.mjs:33:37)
    at YearParser.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/date-fns/parse/_lib/Parser.mjs:5:25)
    at parse (http://localhost:9876/_karma_webpack_/webpack:/node_modules/date-fns/parse.mjs:426:34)

**Comment by outbackStack** [comment]
It will throw an error now if the `dateStr` argument is undefined. This is my case when the data is coming from a remote sites. I just check to make sure it's a string before using `parse`

**Comment by timothylombrana** [comment]
@cheng93 This still seems to be broken in `3.6.0` were you able to find some kind of workaround?

**Comment by acorncom** [comment]
@akaustav there is discussion of this issue in https://github.com/date-fns/date-fns/issues/3707 as well, looks like consumers need to guard themselves vs having the library do so
