### ISSUE TITLE
parseJSON(undefined) trows an error in v3.3.0

### ISSUE THREAD

**Issue by ansgarsteinkamp** [date-fns/date-fns#3676]
According to the docs of parseJSON: "Any other input type or invalid date strings will return an Invalid Date."

In v3.3.0 an error is thrown instead.

**Comment by imwh0im** [comment]
can you example codes?

**Comment by jhndflpp** [comment]
I've run into the same issue with parseISO if you pass an undefined (or null) value.  Resulting error in the console is:
> ERROR TypeError: Cannot read properties of undefined (reading 'split')
>     at splitDateString (parseISO.mjs:108:28)
>     at Module.parseISO (parseISO.mjs:41:23)

This did not occur in the pre 3.x versions (we were formerly using v2.30.0) because it was checking if the passed value was a string before trying to manipulate (split) it.  v2.30.0 has the following lines of code where 3.x does not:
>   if (!(typeof argument === 'string' || Object.prototype.toString.call(argument) === '[object String]')) {
>     return new Date(NaN);
>   }

Looks like parseJSON also had a string check before v3.x and does not afterward.  I don't know if it's part of these changes:
> **BREAKING**: Functions now don’t check the number of passed arguments, delegating this task to type checkers. The functions  are now slimmer because of this.
> **BREAKING** The arguments are not explicitly converted to the target types. Instead, they are passed as is, delegating this task  to type checkers.

but the documentation at least implies that we can (still) expect an invalid date response instead of an error, and it would be helpful if that was the case.

**Comment by paurosellfarre** [comment]
Replicable in ^3.3.x versions (currently 3.3.0, 3.3.1)

**Comment by o-ric** [comment]
I also had the same issue with **parseISO** when passing an undefined or null value as parameter.
According to the docs, I expected an Invalid Date as result, but it threw an error instead.
