### ISSUE TITLE
Upgrading from 2.30.0 to 3.x.x breaks Vite build

### ISSUE THREAD

**Issue by mxsxs2** [date-fns/date-fns#3708]
My projects builds okay with with version 2.30.0. However, I get the following error when updating date-fns to latest:

> vite v5.1.0 building for production...
✓ 317 modules transformed.
error during build:
Error: [commonjs--resolver] Missing "./esm" specifier in "date-fns" package
    at e (file:///home/user/project/src/node_modules/vite/dist/node/chunks/dep-nGG-_oRu.js:47365:25)
    at n (file:///home/user/project/src/node_modules/vite/dist/node/chunks/dep-nGG-_oRu.js:47365:627)
    at o (file:///home/user/project/src/node_modules/vite/dist/node/chunks/dep-nGG-_oRu.js:47365:1297)
    at resolveExportsOrImports (file:///home/user/project/src/node_modules/vite/dist/node/chunks/dep-nGG-_oRu.js:48042:20)
    at resolveDeepImport (file:///home/user/project/src/node_modules/vite/dist/node/chunks/dep-nGG-_oRu.js:48061:31)
    at tryNodeResolve (file:///home/user/project/src/node_modules/vite/dist/node/chunks/dep-nGG-_oRu.js:47786:20)
    at Object.resolveId (file:///home/user/project/src/node_modules/vite/dist/node/chunks/dep-nGG-_oRu.js:47549:28)
    at file:///home/user/project/src/node_modules/rollup/dist/es/shared/node-entry.js:18692:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///home/user/project/src/node_modules/rollup/dist/es/shared/node-entry.js:18592:28)
    at async resolveId (file:///home/user/project/src/node_modules/rollup/dist/es/shared/node-entry.js:17261:26)

I don't have any error from linters (tsc, VCScode) 

I am using:
- date-fns 3.3.1
- Vite 5.0.12 with laravel-vite-plugin 1.0.1 
- NodeJS 20.11.0
- TypeScript 5.3.3

**Comment by kossnocorp** [comment]
Hey! There are no `./esm` strings anywhere in the code. Is it your locale cache, plugin, or another library?

I doubt it's a date-fns issue, but given how many thumbs up there are, I'm down to figuring this out. However, I need a reproduction repo.

**Comment by Alwindh** [comment]
> Hey! There are no `./esm` strings anywhere in the code. Is it your locale cache, plugin, or another library?
> 
> I doubt it's a date-fns issue, but given how many thumbs up there are, I'm down to figuring this out. However, I need a reproduction repo.

On my end it was a conflict with the MUI Adapter component for Localization:

https://mui.com/x/react-date-pickers/adapters-locale/#with-date-fns

Fixed via using the V3 imports instead:

> // with date-fns v2.x
> import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFns';
> // with date-fns v3.x
> import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFnsV3';
> // with date-fns v2.x
> import de from 'date-fns/locale/de';
> // with date-fns v3.x
> import { de } from 'date-fns/locale/de';

**Comment by kossnocorp** [comment]
@Alwindh thank you for sharing it, I was suspecting something like that.

If anyone actually has an issue with date-fns, not other packages, please add a reproduction repo, and I'll reopen the issue.

**Comment by rwb196884** [comment]
Still broken. Last usable version is 2.30.0.

**Comment by mxsxs2** [comment]
I checked again and turns out I had imports like `date-fns/esm`. Once I corrected them the build worked again.

**Comment by aqordeon** [comment]
I have the same issue, then I found out that previously I use
```import { differenceInMilliseconds } from 'date-fns/esm'```, and it's work well

now after update the package, I need to remove the `/esm` to make it work again
```import { differenceInMilliseconds } from 'date-fns'```
