### ISSUE TITLE
[V2] fr (french) language support

### ISSUE THREAD

**Issue by Lakston** [date-fns/date-fns#777]
I'm working on a PR for French language support to match the new API and making good progress.

I have a couple of questions though :

- I have rewritten all the tests but I have a lot of errors, some coming from my test, some coming from the lib tests, even if I comment all my test, running `yarn test` yields errors, is that normal ?

- Concerning my test errors I'm running in a lot of errors like this :
```
      long format
        ✖ short date
          Chrome 67.0.3396 (Mac OS X 10.13.4)
        TypeError: formatLong.date is not a function
            at dateLongFormatter (webpack:///src/format/_lib/longFormatters/index.js:4:24 <- /Users/fab/Code/date-fns/test.js:32988:26)
            at dateTimeLongFormatter (webpack:///src/format/_lib/longFormatters/index.js:35:11 <- /Users/fab/Code/date-fns/test.js:33019:13)
            at webpack:///src/format/index.js:378:15 <- /Users/fab/Code/date-fns/test.js:31460:15
            at Array.map (<anonymous>)
            at format (webpack:///src/format/index.js:374:5 <- myFolder/date-fns/test.js:31456:61)
            at Context.<anonymous> (webpack:///src/locale/fr/test.js:136:28 <-myFolder/date-fns/test.js:77616:44)
```

any hints on what I'm doing wrong ?

- Should I submit a WIP PR or should I wait until I square things out regarding those test errors ?

Thanks for your time !

**Comment by leshakoss** [comment]
@Lakston please submit the PR first so we can take a look at those errors :-)

**Comment by Lakston** [comment]
Thanks ! I submitted the PR, it can be seen [here](https://github.com/date-fns/date-fns/pull/778)
