### ISSUE TITLE
Poor Antarctica!

### ISSUE THREAD

**Issue by kossnocorp** [date-fns/date-fns#96]
We [two failing tests](https://buildkite.com/date-fns/date-fns/builds/25#10bcb76c-499b-4a79-a956-9b6cbe9cc746) for `setISOYear` function in Antarctica's time zone:

```
FAILED TESTS:
  setISOYear
    ✖ allows to pass string
      PhantomJS 1.9.8 (Linux 0.0.0)
    AssertionError:   # set_iso_year_test.js:12
      
      assert.deepEqual(result, new Date(2005, 0, 1))
                       |       |                    
                       |       new Date("2004-12-31T17:00:00.000Z")
                       new Date("2004-12-30T17:00:00.000Z")
      
        at /var/lib/buildkite-agent/builds/date-fns-agent-1/date-fns/date-fns/tmp/tests.js:1533 <- webpack:///~/power-assert/~/empower/lib/decorator.js:66:0
        at decoratedAssert (/var/lib/buildkite-agent/builds/date-fns-agent-1/date-fns/date-fns/tmp/tests.js:9129 <- webpack:///~/power-assert/~/empower/lib/decorate.js:42:0)
        at /var/lib/buildkite-agent/builds/date-fns-agent-1/date-fns/date-fns/tmp/tests.js:26536 <- webpack:///src/__tests__/set_iso_year_test.js:12:29
 
    ✖ allows to pass timestamp
      PhantomJS 1.9.8 (Linux 0.0.0)
    AssertionError:   # set_iso_year_test.js:17
      
      assert.deepEqual(result, new Date(2005, 0, 1))
                       |       |                    
                       |       new Date("2004-12-31T17:00:00.000Z")
                       new Date("2004-12-30T17:00:00.000Z")
      
        at /var/lib/buildkite-agent/builds/date-fns-agent-1/date-fns/date-fns/tmp/tests.js:1533 <- webpack:///~/power-assert/~/empower/lib/decorator.js:66:0
        at decoratedAssert (/var/lib/buildkite-agent/builds/date-fns-agent-1/date-fns/date-fns/tmp/tests.js:9129 <- webpack:///~/power-assert/~/empower/lib/decorate.js:42:0)
        at /var/lib/buildkite-agent/builds/date-fns-agent-1/date-fns/date-fns/tmp/tests.js:26548 <- webpack:///src/__tests__/set_iso_year_test.js:17:29
```

**Comment by LeshaKoss** [comment]
@kossnocorp it is probably the bug of PhantomJS 1.9.8, please use PhantomJS 2.0.0 for automatic tests

**Comment by kossnocorp** [comment]
@LeshaKoss oh shit, right

**Comment by kossnocorp** [comment]
Yup, now it's green! https://buildkite.com/date-fns/date-fns/builds/26
